# -*- coding: utf-8 -*-
"""Representaion Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wYyAPvwVF4LdVdowHtd5ArxsvaE3paMo

# Representation Learning — SimCLR vs MAE
### Comparative Analysis of Contrastive vs Reconstruction-based Self-Supervised Learning

## Section 1 — Setup & Drive
"""

from google.colab import drive
drive.mount('/content/drive')

import os

PROJECT_DIR = "/content/drive/MyDrive/AIMS_SSL"

os.makedirs(PROJECT_DIR, exist_ok=True)
os.makedirs(f"{PROJECT_DIR}/checkpoints", exist_ok=True)

print("Drive folders ready ✅")

import os
os.makedirs('/root/.kaggle', exist_ok=True)
os.rename('kaggle.json', '/root/.kaggle/kaggle.json')
os.chmod('/root/.kaggle/kaggle.json', 0o600)

print("Kaggle API ready ✅")

"""## Section 2 — Dataset

"""

# Download the dataset
os.system('kaggle datasets download -d abtinzandi/obstacle-detection-dataset')

# Unzip it
os.system('unzip obstacle-detection-dataset.zip -d obstacle_dataset')

print("Dataset downloaded ✅")

import os
from torch.utils.data import Dataset, DataLoader
from torchvision import transforms
from PIL import Image

class ObstacleDataset(Dataset):
    def __init__(self, img_dir, transform=None):
        self.img_dir   = img_dir
        self.transform = transform
        self.images    = [f for f in os.listdir(img_dir)
                         if f.endswith(('.jpg', '.jpeg', '.png'))]

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = os.path.join(self.img_dir, self.images[idx])
        image    = Image.open(img_path).convert('RGB')
        if self.transform:
            image = self.transform(image)
        return image

BASE      = 'obstacle_dataset/ROD-Dataset/dataset'
transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
])

train_dataset = ObstacleDataset(BASE + '/train/images', transform=transform)
valid_dataset = ObstacleDataset(BASE + '/valid/images', transform=transform)
test_dataset  = ObstacleDataset(BASE + '/test/images',  transform=transform)

train_loader  = DataLoader(train_dataset, batch_size=64, shuffle=True)
valid_loader  = DataLoader(valid_dataset, batch_size=64, shuffle=False)
test_loader   = DataLoader(test_dataset,  batch_size=64, shuffle=False)

batch = next(iter(train_loader))
print(f"Batch shape: {batch.shape}")
print(f"Train size:  {len(train_dataset)}")

"""## Section 3 — SimCLR Pipeline"""

from torchvision import transforms

class SimCLRAugmentation:
    def __init__(self, image_size=224):
        self.transform = transforms.Compose([
            # Random crop — takes a random portion of the image
            transforms.RandomResizedCrop(image_size, scale=(0.2, 1.0)),
            # Random horizontal flip
            transforms.RandomHorizontalFlip(p=0.5),
            # Random color jitter — changes brightness, contrast, saturation
            transforms.RandomApply([
                transforms.ColorJitter(0.4, 0.4, 0.4, 0.1)
            ], p=0.8),
            # Random grayscale
            transforms.RandomGrayscale(p=0.2),
            transforms.ToTensor(),
            transforms.Normalize(mean=[0.485, 0.456, 0.406],
                                 std=[0.229, 0.224, 0.225])
        ])

    def __call__(self, x):
        # Apply transform TWICE — creates 2 different views
        view1 = self.transform(x)
        view2 = self.transform(x)
        return view1, view2

from PIL import Image
import os

class SimCLRDataset(Dataset):
    def __init__(self, img_dir, transform=None):
        self.img_dir   = img_dir
        self.transform = transform
        self.images    = [f for f in os.listdir(img_dir)
                         if f.endswith(('.jpg', '.jpeg', '.png'))]

    def __len__(self):
        return len(self.images)

    def __getitem__(self, idx):
        img_path = os.path.join(self.img_dir, self.images[idx])
        image    = Image.open(img_path).convert('RGB')
        if self.transform:
            view1, view2 = self.transform(image)  # returns 2 views
        return view1, view2   # no labels needed

# Create dataset with SimCLR augmentations
augmentation     = SimCLRAugmentation(image_size=224)
simclr_dataset   = SimCLRDataset(BASE + '/train/images', transform=augmentation)
simclr_loader    = DataLoader(simclr_dataset, batch_size=64, shuffle=True)

# Sanity check
view1, view2 = next(iter(simclr_loader))
print(f"View 1 shape: {view1.shape}")   # [64, 3, 224, 224]
print(f"View 2 shape: {view2.shape}")   # [64, 3, 224, 224]

import torch
import torch.nn as nn
from torchvision import models

class SimCLREncoder(nn.Module):
    def __init__(self, embedding_dim=128):
        super().__init__()

        # Load pretrained ResNet18
        resnet = models.resnet18(weights = None)

        self.backbone = nn.Sequential(*list(resnet.children())[:-1])
        # now backbone outputs [B, 512, 1, 1]

        # Projection head — maps encoder output to embedding space
        self.projection_head = nn.Sequential(
            nn.Linear(512, 512),    # 512 → 512
            nn.ReLU(),
            nn.Linear(512, embedding_dim)   # 512 → 128
        )

    def forward(self, x):
        # x: [B, 3, 224, 224]
        features = self.backbone(x)         # [B, 512, 1, 1]
        features = features.flatten(1)      # [B, 512]
        embeddings = self.projection_head(features)  # [B, 128]
        return embeddings

import torch
import torch.nn.functional as F

class NTXentLoss(nn.Module):
    def __init__(self, temperature=0.5):
        super().__init__()
        self.temperature = temperature

    def forward(self, view1_emb, view2_emb):
        """
        view1_emb: [B, 128] — embeddings of first views
        view2_emb: [B, 128] — embeddings of second views
        """
        B = view1_emb.shape[0]

        # Step 1 — normalize embeddings to unit sphere
        # this makes dot product = cosine similarity
        z1 = F.normalize(view1_emb, dim=1)   # [B, 128]
        z2 = F.normalize(view2_emb, dim=1)   # [B, 128]

        # Step 2 — concatenate all embeddings together
        # [z1_1, z1_2, ..., z1_B, z2_1, z2_2, ..., z2_B]
        z  = torch.cat([z1, z2], dim=0)      # [2B, 128]

        # Step 3 — compute similarity between every pair
        # dot product of every embedding with every other
        sim = torch.mm(z, z.T) / self.temperature  # [2B, 2B]

        # Step 4 — remove self similarity (diagonal)
        # an image shouldn't be compared to itself
        mask = torch.eye(
            2 * B,
            dtype=torch.bool,
            device=sim.device
        )
        sim.masked_fill_(mask, float('-inf'))

        # Step 5 — build labels
        # for image i in first half, its positive is i + B (second half)
        # for image i in second half, its positive is i - B (first half)
        labels = torch.cat([
            torch.arange(B, 2 * B , device = sim.device),   # first half points to second half
            torch.arange(0, B , device = sim.device)        # second half points to first half
        ])                            # [2B]

        # Step 6 — cross entropy loss
        # for each embedding, treat positive as the correct class
        loss = F.cross_entropy(sim, labels)
        return loss

import torch
import torch.nn as nn

device    = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using: {device}")

model     = SimCLREncoder(embedding_dim=128).to(device)
criterion = NTXentLoss(temperature=0.5)
optimizer = torch.optim.Adam(model.parameters(), lr=3e-4)

# Resume training if checkpoint exists
import os

checkpoint_path = f"{PROJECT_DIR}/checkpoints/simclr_latest.pth"

start_epoch = 0

if os.path.exists(checkpoint_path):

    checkpoint = torch.load(checkpoint_path)

    model.load_state_dict(
        checkpoint['model_state_dict']
    )

    optimizer.load_state_dict(
        checkpoint['optimizer_state_dict']
    )

    start_epoch = checkpoint['epoch'] + 1

    print(f"Resuming from epoch {start_epoch}")

# Training loop
EPOCHS = 5

for epoch in range(start_epoch , EPOCHS):
    total_loss = 0

    for view1, view2 in simclr_loader:
        # move to GPU
        view1 = view1.to(device)
        view2 = view2.to(device)

        # forward pass — get embeddings for both views
        emb1 = model(view1)   # [B, 128]
        emb2 = model(view2)   # [B, 128]

        # compute contrastive loss
        loss = criterion(emb1, emb2)

        # standard 5 steps
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        total_loss += loss.item()

    # average loss across all batches this epoch
    avg_loss = total_loss / len(simclr_loader)

    print(f"Epoch {epoch+1}/{EPOCHS}  Loss: {avg_loss:.4f}")

    torch.save({
    'epoch': epoch,
    'model_state_dict': model.state_dict(),
    'optimizer_state_dict': optimizer.state_dict(),
    'loss': avg_loss
    },f"{PROJECT_DIR}/checkpoints/simclr_latest.pth")

torch.save(
    model.state_dict(),
    f"{PROJECT_DIR}/checkpoints/simclr_encoder_final.pth"
)

print("SimCLR encoder saved ✅")

import numpy as np

# Load the saved encoder
model = SimCLREncoder(embedding_dim=128).to(device)
model.load_state_dict(torch.load(f"{PROJECT_DIR}/checkpoints/simclr_encoder_final.pth"))
model.eval()   # evaluation mode — no dropout, no gradient

eval_transform = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485, 0.456, 0.406],
                         std=[0.229, 0.224, 0.225])
])

eval_dataset = ObstacleDataset(BASE + '/valid/images', transform=eval_transform)
eval_loader  = DataLoader(eval_dataset, batch_size=64, shuffle=False)

# Extract embeddings
all_embeddings = []

with torch.no_grad():
    for images in eval_loader:
        images     = images.to(device)
        embeddings = model(images)          # [B, 128]
        all_embeddings.append(embeddings.cpu().numpy())

# Stack all batches into one array
all_embeddings = np.concatenate(all_embeddings, axis=0)
print(f"Embeddings shape: {all_embeddings.shape}")   # [3511, 128]

# Save embeddings
np.save(f"{PROJECT_DIR}/simclr_embeddings.npy", all_embeddings)
print("Embeddings saved ✅")

"""## Section 4 — MAE Pipeline"""

import torch
import torch.nn as nn

class PatchEmbedding(nn.Module):
    def __init__(self, image_size=224, patch_size=16, in_channels=3, embed_dim=192):
        super().__init__()

        self.patch_size  = patch_size
        self.num_patches = (image_size // patch_size) ** 2  # 196

        self.projection = nn.Conv2d(
            in_channels,   # 3 (RGB)
            embed_dim,     # 192 — each patch becomes a 192-dim vector
            kernel_size=patch_size,
            stride=patch_size
        )

    def forward(self, x):
        # x: [B, 3, 224, 224]
        x = self.projection(x)   # [B, 192, 14, 14]
        x = x.flatten(2)         # [B, 192, 196]  — flatten the 14x14 grid
        x = x.transpose(1, 2)    # [B, 196, 192]  — sequence of 196 patch vectors
        return x

class RandomMasking(nn.Module):
    def __init__(self, mask_ratio=0.75):
        super().__init__()
        self.mask_ratio = mask_ratio

    def forward(self, x):
        """
        x: [B, 196, 192] — full sequence of patch embeddings
        """
        B, N, D = x.shape
        num_keep = int(N * (1 - self.mask_ratio)) # 196 * 0.25 = 49

        # Step 1 — generate random noise and argsort it
        noise   = torch.rand(B, N, device=x.device)   # [B, 196]
        ids_shuffle  = torch.argsort(noise, dim=1)     # [B, 196] — random order
        ids_restore  = torch.argsort(ids_shuffle, dim=1) # [B, 196] — to undo shuffle later

        # Step 2 — keep only the first num_keep indices (the "visible" patches)
        ids_keep     = ids_shuffle[:, :num_keep]       # [B, 49]

        # Step 3 — gather the visible patch embeddings
        # torch.gather picks specific indices along a dimension
        x_masked = torch.gather(
            x,
            dim=1,
            index=ids_keep.unsqueeze(-1).expand(-1, -1, D)
        )                                              # [B, 49, 192]

        # Step 4 — build a binary mask (0=visible, 1=masked)
        # used later to compute loss only on masked patches
        mask = torch.ones(B, N, device=x.device)
        mask[:, :num_keep] = 0
        # unshuffle to match original patch positions
        mask = torch.gather(mask, dim=1, index=ids_restore)  # [B, 196]

        return x_masked, mask, ids_restore

class MultiHeadAttention(nn.Module):
    def __init__(self, embed_dim=192, num_heads=3):
        super().__init__()
        self.num_heads  = num_heads
        self.head_dim   = embed_dim // num_heads
        self.scale      = self.head_dim ** -0.5

        # Projects input into Q, K, V in one shot
        self.qkv        = nn.Linear(embed_dim, embed_dim * 3)
        self.proj       = nn.Linear(embed_dim, embed_dim)

    def forward(self, x):
        B, N, D = x.shape

        # Compute Q, K, V and split into heads
        qkv = self.qkv(x)                             # [B, N, 3*192]
        qkv = qkv.reshape(B, N, 3, self.num_heads, self.head_dim)
        qkv = qkv.permute(2, 0, 3, 1, 4)             # [3, B, heads, N, head_dim]
        q, k, v = qkv[0], qkv[1], qkv[2]             # each: [B, heads, N, head_dim]

        # Scaled dot-product attention
        attn = (q @ k.transpose(-2, -1)) * self.scale # [B, heads, N, N]
        attn = attn.softmax(dim=-1)

        # Weighted sum of values
        x = (attn @ v)                                 # [B, heads, N, head_dim]
        x = x.transpose(1, 2).reshape(B, N, D)        # [B, N, 192]
        x = self.proj(x)
        return x


class TransformerBlock(nn.Module):
    def __init__(self, embed_dim=192, num_heads=3, mlp_ratio=4.0):
        super().__init__()
        self.norm1 = nn.LayerNorm(embed_dim)
        self.attn  = MultiHeadAttention(embed_dim, num_heads)
        self.norm2 = nn.LayerNorm(embed_dim)

        # Small feedforward network inside each block
        mlp_dim    = int(embed_dim * mlp_ratio)        # 192 * 4 = 768
        self.mlp   = nn.Sequential(
            nn.Linear(embed_dim, mlp_dim),
            nn.GELU(),                                 # smoother than ReLU, standard in ViTs
            nn.Linear(mlp_dim, embed_dim)
        )

    def forward(self, x):
        # Residual connections — x is added back after each sub-layer
        x = x + self.attn(self.norm1(x))
        x = x + self.mlp(self.norm2(x))
        return x


class MAEEncoder(nn.Module):
    def __init__(self, image_size=224, patch_size=16,
                 embed_dim=192, depth=6, num_heads=3):
        super().__init__()

        self.patch_embed  = PatchEmbedding(image_size, patch_size, 3, embed_dim)
        self.masking      = RandomMasking(mask_ratio=0.75)

        # CLS token — a learnable summary vector prepended to the sequence
        self.cls_token    = nn.Parameter(torch.zeros(1, 1, embed_dim))

        # Positional embeddings — tell the model where each patch is spatially
        num_patches       = self.patch_embed.num_patches
        self.pos_embed    = nn.Parameter(torch.zeros(1, num_patches + 1, embed_dim))

        # Stack of Transformer blocks
        self.blocks       = nn.ModuleList([
            TransformerBlock(embed_dim, num_heads)
            for _ in range(depth)                      # 6 layers
        ])
        self.norm         = nn.LayerNorm(embed_dim)

        self._init_weights()

    def _init_weights(self):
        # Small normal init — standard practice for ViTs
        nn.init.normal_(self.cls_token,  std=0.02)
        nn.init.normal_(self.pos_embed,  std=0.02)

    def forward(self, x):
        # Step 1 — patch embedding
        x = self.patch_embed(x)                        # [B, 196, 192]

        # Step 2 — add positional embeddings (skip CLS position)
        x = x + self.pos_embed[:, 1:, :]              # [B, 196, 192]

        # Step 3 — random masking → keep only 49 visible patches
        x, mask, ids_restore = self.masking(x)         # [B, 49, 192]

        # Step 4 — prepend CLS token
        cls_token = self.cls_token + self.pos_embed[:, :1, :]
        cls_token = cls_token.expand(x.shape[0], -1, -1)  # [B, 1, 192]
        x         = torch.cat([cls_token, x], dim=1)   # [B, 50, 192]

        # Step 5 — pass through Transformer blocks
        for block in self.blocks:
            x = block(x)
        x = self.norm(x)                               # [B, 50, 192]

        return x, mask, ids_restore

class MAEDecoder(nn.Module):
    def __init__(self, num_patches=196, embed_dim=192,
                 decoder_embed_dim=96, decoder_depth=2,
                 decoder_num_heads=3, patch_size=16):
        super().__init__()

        self.patch_size = patch_size

        # Project encoder dim (192) → decoder dim (96)
        # decoder is intentionally lightweight
        self.decoder_embed = nn.Linear(embed_dim, decoder_embed_dim)

        # Mask token — single learnable vector used for all masked positions
        self.mask_token    = nn.Parameter(torch.zeros(1, 1, decoder_embed_dim))

        # Decoder positional embeddings — all 196 patches + CLS
        self.decoder_pos_embed = nn.Parameter(
            torch.zeros(1, num_patches + 1, decoder_embed_dim)
        )

        # Lightweight transformer blocks (only 2, vs 6 in encoder)
        self.decoder_blocks = nn.ModuleList([
            TransformerBlock(decoder_embed_dim, decoder_num_heads)
            for _ in range(decoder_depth)
        ])

        self.decoder_norm = nn.LayerNorm(decoder_embed_dim)

        # Final projection — each patch token → 768 pixel values (16*16*3)
        self.decoder_pred = nn.Linear(
            decoder_embed_dim,
            patch_size * patch_size * 3            # 96 → 768
        )

        self._init_weights()

    def _init_weights(self):
        nn.init.normal_(self.mask_token,        std=0.02)
        nn.init.normal_(self.decoder_pos_embed, std=0.02)

    def forward(self, x, ids_restore):
        """
        x           : [B, 50, 192]  — encoder output (CLS + 49 visible)
        ids_restore : [B, 196]      — how to unshuffle back to original order
        """
        # Step 1 — project to decoder dimension
        x = self.decoder_embed(x)                     # [B, 50, 96]

        # Step 2 — remove CLS token before unshuffling patches
        x_patches = x[:, 1:, :]                       # [B, 49, 96]

        # Step 3 — create mask tokens for the 147 missing patches
        B          = x.shape[0]
        mask_tokens = self.mask_token.expand(
            B, ids_restore.shape[1] - x_patches.shape[1], -1
        )                                              # [B, 147, 96]

        # Step 4 — concatenate visible + mask tokens, then unshuffle
        x_full = torch.cat([x_patches, mask_tokens], dim=1)  # [B, 196, 96]
        x_full = torch.gather(
            x_full,
            dim=1,
            index=ids_restore.unsqueeze(-1).expand(-1, -1, x_full.shape[-1])
        )                                              # [B, 196, 96] — original order restored

        # Step 5 — prepend CLS token back
        cls = x[:, :1, :]                              # [B, 1, 96]
        x_full = torch.cat([cls, x_full], dim=1)       # [B, 197, 96]

        # Step 6 — add positional embeddings
        x_full = x_full + self.decoder_pos_embed       # [B, 197, 96]

        # Step 7 — transformer blocks
        for block in self.decoder_blocks:
            x_full = block(x_full)
        x_full = self.decoder_norm(x_full)             # [B, 197, 96]

        # Step 8 — predict pixel values, remove CLS token
        x_full = self.decoder_pred(x_full)             # [B, 197, 768]
        x_full = x_full[:, 1:, :]                      # [B, 196, 768] — drop CLS

        return x_full

class MAE(nn.Module):
    def __init__(self, image_size=224, patch_size=16,
                 embed_dim=192, depth=6, num_heads=3,
                 decoder_embed_dim=96, decoder_depth=2,
                 decoder_num_heads=3):
        super().__init__()

        self.patch_size = patch_size

        self.encoder = MAEEncoder(
            image_size = image_size,
            patch_size = patch_size,
            embed_dim  = embed_dim,
            depth      = depth,
            num_heads  = num_heads
        )

        self.decoder = MAEDecoder(
            num_patches       = (image_size // patch_size) ** 2,
            embed_dim         = embed_dim,
            decoder_embed_dim = decoder_embed_dim,
            decoder_depth     = decoder_depth,
            decoder_num_heads = decoder_num_heads,
            patch_size        = patch_size
        )

    def patchify(self, imgs):
        """
        Split images into patches — gives us the reconstruction target.
        imgs   : [B, 3, 224, 224]
        return : [B, 196, 768]
        """
        p  = self.patch_size                           # 16
        h  = w = imgs.shape[2] // p                   # 14
        x  = imgs.reshape(imgs.shape[0], 3, h, p, w, p)
        x  = torch.einsum('nchpwq->nhwpqc', x)        # rearrange dimensions
        x  = x.reshape(imgs.shape[0], h * w, p*p*3)   # [B, 196, 768]
        return x

    def forward(self, imgs):
        # Encode — get visible patch embeddings + mask info
        enc_output, mask, ids_restore = self.encoder(imgs)

        # Decode — reconstruct all 196 patches
        pred = self.decoder(enc_output, ids_restore)   # [B, 196, 768]

        # Reconstruction target — actual pixel values per patch
        target = self.patchify(imgs)                   # [B, 196, 768]

        # MSE loss — only on masked patches (mask=1 means masked)
        loss = (pred - target) ** 2                    # [B, 196, 768]
        loss = loss.mean(dim=-1)                       # [B, 196] — mean over pixels per patch
        loss = (loss * mask).sum() / mask.sum()        # average only over masked patches

        return loss, pred, mask

import os
import torch

device    = 'cuda' if torch.cuda.is_available() else 'cpu'
print(f"Using: {device}")

mae_model   = MAE(
    image_size        = 224,
    patch_size        = 16,
    embed_dim         = 192,
    depth             = 6,
    num_heads         = 3,
    decoder_embed_dim = 96,
    decoder_depth     = 2,
    decoder_num_heads = 3
).to(device)

optimizer = torch.optim.AdamW(mae_model.parameters(), lr=1.5e-4, weight_decay=0.05)
# AdamW instead of Adam — weight decay is standard practice for ViTs

# Resume if checkpoint exists
mae_checkpoint_path = f"{PROJECT_DIR}/checkpoints/mae_latest.pth"
start_epoch         = 0

if os.path.exists(mae_checkpoint_path):
    checkpoint = torch.load(mae_checkpoint_path)
    mae_model.load_state_dict(checkpoint['model_state_dict'])
    optimizer.load_state_dict(checkpoint['optimizer_state_dict'])
    start_epoch = checkpoint['epoch'] + 1
    print(f"Resuming from epoch {start_epoch}")

# Training loop
EPOCHS = 5

for epoch in range(start_epoch, EPOCHS):
    mae_model.train()
    total_loss = 0

    for images in train_loader:           # plain images [B, 3, 224, 224]
        images = images.to(device)

        # forward pass — returns loss, predictions, mask
        loss, _, _ = mae_model(images)

        optimizer.zero_grad()
        loss.backward()

        # gradient clipping — prevents exploding gradients in transformers
        torch.nn.utils.clip_grad_norm_(mae_model.parameters(), max_norm=1.0)

        optimizer.step()
        total_loss += loss.item()

    avg_loss = total_loss / len(train_loader)
    print(f"Epoch {epoch+1}/{EPOCHS}  Loss: {avg_loss:.4f}")

    torch.save({
        'epoch'               : epoch,
        'model_state_dict'    : mae_model.state_dict(),
        'optimizer_state_dict': optimizer.state_dict(),
        'loss'                : avg_loss
    }, mae_checkpoint_path)

torch.save(
    mae_model.encoder.state_dict(),
    f"{PROJECT_DIR}/checkpoints/mae_encoder_final.pth"
)
print("MAE encoder saved ✅")

import numpy as np

#Load the saved MAE encoder
mae_encoder = MAEEncoder(
    image_size = 224,
    patch_size = 16,
    embed_dim  = 192,
    depth      = 6,
    num_heads  = 3
).to(device)

mae_encoder.load_state_dict(
    torch.load(f"{PROJECT_DIR}/checkpoints/mae_encoder_final.pth")
)
mae_encoder.eval()

class MAEEncoderInference(nn.Module):
    def __init__(self, mae_encoder):
        super().__init__()
        self.patch_embed = mae_encoder.patch_embed
        self.cls_token   = mae_encoder.cls_token
        self.pos_embed   = mae_encoder.pos_embed
        self.blocks      = mae_encoder.blocks
        self.norm        = mae_encoder.norm

    def forward(self, x):
        # Patch embedding
        x = self.patch_embed(x)                        # [B, 196, 192]

        # Add positional embeddings
        x = x + self.pos_embed[:, 1:, :]              # [B, 196, 192]

        # Prepend CLS token — no masking this time
        cls_token = self.cls_token + self.pos_embed[:, :1, :]
        cls_token = cls_token.expand(x.shape[0], -1, -1)
        x         = torch.cat([cls_token, x], dim=1)  # [B, 197, 192]

        # Pass through transformer blocks
        for block in self.blocks:
            x = block(x)
        x = self.norm(x)                               # [B, 197, 192]

        # Return CLS token only — image level representation
        return x[:, 0, :]                              # [B, 192]

# ── Extract embeddings ─────────────────────────────────
inference_model = MAEEncoderInference(mae_encoder).to(device)
inference_model.eval()

all_mae_embeddings = []

with torch.no_grad():
    for images in eval_loader:                         # same eval_loader from SimCLR
        images     = images.to(device)
        embeddings = inference_model(images)           # [B, 192]
        all_mae_embeddings.append(embeddings.cpu().numpy())

all_mae_embeddings = np.concatenate(all_mae_embeddings, axis=0)
print(f"MAE embeddings shape: {all_mae_embeddings.shape}")  # [N, 192]

# Save embeddings
np.save(f"{PROJECT_DIR}/mae_embeddings.npy", all_mae_embeddings)
print("MAE embeddings saved ✅")

import os
import numpy as np

label_path = 'obstacle_dataset/ROD-Dataset/dataset/valid/labels'
image_path = 'obstacle_dataset/ROD-Dataset/dataset/valid/images'

# Get image list in same order as eval_loader
image_files = sorted([f for f in os.listdir(image_path)
                      if f.endswith(('.jpg', '.jpeg', '.png'))])

labels = []
for img_file in image_files:
    label_file = os.path.splitext(img_file)[0] + '.txt'
    label_file_path = os.path.join(label_path, label_file)

    if os.path.exists(label_file_path):
        with open(label_file_path, 'r') as f:
            lines = f.read().strip().split('\n')
        # Take the first object's class ID as image-level label
        first_class = int(lines[0].split()[0]) if lines and lines[0] else -1
    else:
        first_class = -1

    labels.append(first_class)

labels = np.array(labels)

print(f"Total labels     : {len(labels)}")
print(f"Unique classes   : {np.unique(labels)}")
print(f"Class counts     :")
for cls in np.unique(labels):
    print(f"  class {cls}: {(labels == cls).sum()} images")

"""## Section 5 — Evaluation & Comparison"""

from sklearn.manifold import TSNE
from sklearn.preprocessing import normalize
import matplotlib.pyplot as plt
import numpy as np

# Load embeddings
simclr_emb = np.load(f"{PROJECT_DIR}/simclr_embeddings.npy")
mae_emb    = np.load(f"{PROJECT_DIR}/mae_embeddings.npy")

# Normalize
simclr_emb = normalize(simclr_emb)
mae_emb    = normalize(mae_emb)

print("Running t-SNE on SimCLR embeddings...")
tsne      = TSNE(n_components=2, random_state=42, perplexity=40, n_iter=1000)
simclr_2d = tsne.fit_transform(simclr_emb)

print("Running t-SNE on MAE embeddings...")
tsne   = TSNE(n_components=2, random_state=42, perplexity=40, n_iter=1000)
mae_2d = tsne.fit_transform(mae_emb)

print("t-SNE done ✅")

# Plot
fig, axes = plt.subplots(1, 2, figsize=(18, 7))

scatter1 = axes[0].scatter(
    simclr_2d[:, 0], simclr_2d[:, 1],
    c=labels, cmap='tab20',
    s=4, alpha=0.6
)
axes[0].set_title('SimCLR — t-SNE (25 classes)', fontsize=14)
axes[0].axis('off')
plt.colorbar(scatter1, ax=axes[0], label='Class ID')

scatter2 = axes[1].scatter(
    mae_2d[:, 0], mae_2d[:, 1],
    c=labels, cmap='tab20',
    s=4, alpha=0.6
)
axes[1].set_title('MAE — t-SNE (25 classes)', fontsize=14)
axes[1].axis('off')
plt.colorbar(scatter2, ax=axes[1], label='Class ID')

plt.suptitle('Latent Space Comparison: SimCLR vs MAE', fontsize=16)
plt.tight_layout()
plt.savefig(f"{PROJECT_DIR}/tsne_comparison.png", dpi=150, bbox_inches='tight')
plt.show()
print("Plot saved ✅")

# pip install first
!pip install umap-learn -q

import umap
import matplotlib.pyplot as plt

print("Running UMAP on SimCLR embeddings...")
reducer     = umap.UMAP(n_components=2, random_state=42, n_neighbors=30, min_dist=0.1)
simclr_umap = reducer.fit_transform(simclr_emb)

print("Running UMAP on MAE embeddings...")
reducer  = umap.UMAP(n_components=2, random_state=42, n_neighbors=30, min_dist=0.1)
mae_umap = reducer.fit_transform(mae_emb)

fig, axes = plt.subplots(1, 2, figsize=(18, 7))

scatter1 = axes[0].scatter(simclr_umap[:, 0], simclr_umap[:, 1],
                            c=labels, cmap='tab20', s=4, alpha=0.6)
axes[0].set_title('SimCLR — UMAP', fontsize=14)
axes[0].axis('off')
plt.colorbar(scatter1, ax=axes[0], label='Class ID')

scatter2 = axes[1].scatter(mae_umap[:, 0], mae_umap[:, 1],
                            c=labels, cmap='tab20', s=4, alpha=0.6)
axes[1].set_title('MAE — UMAP', fontsize=14)
axes[1].axis('off')
plt.colorbar(scatter2, ax=axes[1], label='Class ID')

plt.suptitle('UMAP Comparison: SimCLR vs MAE', fontsize=16)
plt.tight_layout()
plt.savefig(f"{PROJECT_DIR}/umap_comparison.png", dpi=150, bbox_inches='tight')
plt.show()
print("UMAP plot saved ✅")

from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import normalize
import numpy as np

def knn_accuracy(embeddings, labels, k=5):
    """
    For each sample, find k nearest neighbours and
    predict class by majority vote. Returns accuracy.
    """
    knn = KNeighborsClassifier(
        n_neighbors = k,
        metric      = 'cosine',    # cosine distance works best for normalized embeddings
        n_jobs      = -1           # use all CPU cores
    )

    # 5-fold cross validation — more reliable than a single train/test split
    scores = cross_val_score(knn, embeddings, labels, cv=5, scoring='accuracy')
    return scores.mean(), scores.std()


# ── Run KNN for both models ────────────────────────────
print("Running KNN evaluation...")
print()

for k in [1, 5, 10, 20]:
    simclr_acc, simclr_std = knn_accuracy(simclr_emb, labels, k=k)
    mae_acc,    mae_std    = knn_accuracy(mae_emb,    labels, k=k)

    print(f"K={k:2d}  |  SimCLR: {simclr_acc*100:.2f}% ± {simclr_std*100:.2f}%"
          f"  |  MAE: {mae_acc*100:.2f}% ± {mae_std*100:.2f}%")

print()
print("KNN evaluation done ✅")

from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, davies_bouldin_score

def clustering_metrics(embeddings, n_clusters=25):
    """
    Fit KMeans and measure cluster quality.
    Silhouette: higher is better  (range -1 to 1)
    Davies-Bouldin: lower is better (range 0 to ∞)
    """
    km = KMeans(n_clusters=n_clusters, random_state=42, n_init=10)
    cluster_labels = km.fit_predict(embeddings)

    sil = silhouette_score(embeddings, cluster_labels, metric='cosine')
    db  = davies_bouldin_score(embeddings, cluster_labels)

    return sil, db

print("Running clustering metrics...")
print()

simclr_sil, simclr_db = clustering_metrics(simclr_emb, n_clusters=25)
mae_sil,    mae_db    = clustering_metrics(mae_emb,    n_clusters=25)

print(f"{'Metric':<25} {'SimCLR':>10} {'MAE':>10} {'Winner':>10}")
print("-" * 55)
print(f"{'Silhouette (↑ better)':<25} {simclr_sil:>10.4f} {mae_sil:>10.4f}"
      f" {'SimCLR' if simclr_sil > mae_sil else 'MAE':>10}")
print(f"{'Davies-Bouldin (↓ better)':<25} {simclr_db:>10.4f} {mae_db:>10.4f}"
      f" {'SimCLR' if simclr_db < mae_db else 'MAE':>10}")

print()
print("Clustering metrics done ✅")

import torch
import torch.nn.functional as F

def alignment(embeddings, labels, alpha=2):
    """
    Measures how close embeddings of same-class samples are.
    Lower is better.
    Alignment = avg distance between positive pairs (same class)
    """
    embeddings = torch.tensor(embeddings)
    labels     = torch.tensor(labels)

    embeddings = F.normalize(embeddings, dim=1)

    total, count = 0.0, 0
    # sample a subset for speed — all pairs is too slow
    for cls in torch.unique(labels):
        idx  = (labels == cls).nonzero(as_tuple=True)[0]
        if len(idx) < 2:
            continue
        emb  = embeddings[idx]                        # all embeddings of this class
        # pairwise distances within class
        diff = emb.unsqueeze(0) - emb.unsqueeze(1)    # [N, N, D]
        dist = diff.norm(dim=2)                        # [N, N]
        # upper triangle only (avoid double counting)
        mask = torch.triu(torch.ones(len(idx), len(idx)), diagonal=1).bool()
        total += dist[mask].pow(alpha).mean().item()
        count += 1

    return total / count if count > 0 else 0.0


def uniformity(embeddings, t=2):
    """
    Measures how uniformly embeddings are spread across the unit sphere.
    Lower is better.
    Uniformity = log avg pairwise Gaussian kernel
    """
    embeddings = torch.tensor(embeddings)
    embeddings = F.normalize(embeddings, dim=1)

    # subsample 1000 points for speed
    idx        = torch.randperm(len(embeddings))[:1000]
    embeddings = embeddings[idx]

    sq_dists   = torch.pdist(embeddings, p=2).pow(2)  # pairwise squared distances
    return sq_dists.mul(-t).exp().mean().log().item()


print("Computing alignment & uniformity...")
print()

simclr_align = alignment(simclr_emb, labels)
mae_align    = alignment(mae_emb,    labels)

simclr_unif  = uniformity(simclr_emb)
mae_unif     = uniformity(mae_emb)

print(f"{'Metric':<25} {'SimCLR':>10} {'MAE':>10} {'Winner':>10}")
print("-" * 55)
print(f"{'Alignment (↓ better)':<25} {simclr_align:>10.4f} {mae_align:>10.4f}"
      f" {'SimCLR' if simclr_align < mae_align else 'MAE':>10}")
print(f"{'Uniformity (↓ better)':<25} {simclr_unif:>10.4f} {mae_unif:>10.4f}"
      f" {'SimCLR' if simclr_unif < mae_unif else 'MAE':>10}")

print()
print("Alignment & uniformity done ✅")

import numpy as np
from sklearn.metrics.pairwise import cosine_similarity

def retrieval_precision_at_k(embeddings, labels, k=5):
    """
    For each image, find top-K most similar images.
    Precision@K = fraction of top-K that share the same class.
    """
    # Compute full cosine similarity matrix
    sim_matrix = cosine_similarity(embeddings)   # [N, N]

    # Set diagonal to -1 so image doesn't retrieve itself
    np.fill_diagonal(sim_matrix, -1)

    precisions = []
    for i in range(len(labels)):
        # Get indices of top-K most similar images
        top_k_idx      = np.argsort(sim_matrix[i])[::-1][:k]
        top_k_labels   = labels[top_k_idx]

        # Precision = how many of top-K share same class
        correct        = (top_k_labels == labels[i]).sum()
        precisions.append(correct / k)

    return np.mean(precisions)


print("Running image retrieval evaluation...")
print()

for k in [1, 5, 10, 20]:
    simclr_p = retrieval_precision_at_k(simclr_emb, labels, k=k)
    mae_p    = retrieval_precision_at_k(mae_emb,    labels, k=k)

    print(f"Precision@{k:<3}  |  SimCLR: {simclr_p*100:.2f}%"
          f"  |  MAE: {mae_p*100:.2f}%"
          f"  |  Winner: {'SimCLR' if simclr_p > mae_p else 'MAE'}")

print()
print("Retrieval evaluation done ✅")

import torch
import numpy as np
import matplotlib.pyplot as plt
from torchvision import transforms
from PIL import Image
import os

# ── We need a special MAE that returns the masked image too ──
def reconstruct_samples(mae_model, img_dir, num_samples=5):

    # Simple transform — same as eval
    transform = transforms.Compose([
        transforms.Resize((224, 224)),
        transforms.ToTensor(),
        transforms.Normalize(mean=[0.485, 0.456, 0.406],
                             std=[0.229, 0.224, 0.225])
    ])

    # Inverse normalize — to convert tensor back to viewable image
    inv_normalize = transforms.Normalize(
        mean=[-0.485/0.229, -0.456/0.224, -0.406/0.225],
        std=[1/0.229, 1/0.224, 1/0.225]
    )

    image_files = sorted([f for f in os.listdir(img_dir)
                         if f.endswith(('.jpg', '.jpeg', '.png'))])[:num_samples]

    fig, axes = plt.subplots(num_samples, 3, figsize=(12, 4 * num_samples))
    fig.suptitle('MAE Reconstruction', fontsize=16)

    mae_model.eval()

    for i, img_file in enumerate(image_files):
        # Load image
        img_path = os.path.join(img_dir, img_file)
        img      = Image.open(img_path).convert('RGB')
        tensor   = transform(img).unsqueeze(0).to(device)  # [1, 3, 224, 224]

        with torch.no_grad():
            loss, pred, mask = mae_model(tensor)

        # ── Reconstruct the masked image ──────────────────
        # pred   : [1, 196, 768] — predicted pixel values per patch
        # mask   : [1, 196]      — 1=masked, 0=visible
        p   = mae_model.patch_size                          # 16
        h   = w = 224 // p                                  # 14

        # Unpatchify prediction → full image tensor
        pred_img = pred.reshape(1, h, w, p, p, 3)
        pred_img = torch.einsum('nhwpqc->nchpwq', pred_img)
        pred_img = pred_img.reshape(1, 3, 224, 224)        # [1, 3, 224, 224]

        # Build masked image — black out masked patches
        mask_vis = mask.reshape(1, h, w)                    # [1, 14, 14]
        mask_vis = mask_vis.unsqueeze(1)                    # [1, 1, 14, 14]
        mask_vis = mask_vis.repeat(1, 3, 1, 1)             # [1, 3, 14, 14]
        mask_vis = torch.nn.functional.interpolate(
            mask_vis.float(), scale_factor=p               # upscale to [1, 3, 224, 224]
        )

        # Apply mask to original — zero out masked regions
        masked_img = tensor * (1 - mask_vis)               # visible patches only

        # ── Convert tensors to numpy for plotting ─────────
        def to_img(t):
            t = inv_normalize(t.squeeze(0).cpu())
            t = torch.clamp(t, 0, 1)
            return t.permute(1, 2, 0).numpy()

        orig_np    = to_img(tensor)
        masked_np  = to_img(masked_img)
        pred_np    = to_img(pred_img)

        # ── Plot row ───────────────────────────────────────
        axes[i][0].imshow(orig_np)
        axes[i][0].set_title('Original')
        axes[i][0].axis('off')

        axes[i][1].imshow(masked_np)
        axes[i][1].set_title('Masked (75% hidden)')
        axes[i][1].axis('off')

        axes[i][2].imshow(pred_np)
        axes[i][2].set_title('MAE Reconstruction')
        axes[i][2].axis('off')

    plt.tight_layout()
    plt.savefig(f"{PROJECT_DIR}/mae_reconstruction.png", dpi=150, bbox_inches='tight')
    plt.show()
    print("Reconstruction plot saved ✅")


# ── Run it ─────────────────────────────────────────────
img_dir = 'obstacle_dataset/ROD-Dataset/dataset/valid/images'
reconstruct_samples(mae_model, img_dir, num_samples=5)

"""## Section 6 — Results Summary"""

import matplotlib.pyplot as plt
import numpy as np


metrics = {
    'KNN @20'         : (12.33, 11.17),
    'Silhouette'      : (32.64, 25.45),
    'Davies-Bouldin'  : (1.488, 1.660),
    'Alignment'       : (1.931, 0.779),
    'Uniformity'      : (3.096, 0.938),
}

# Print summary table
print(f"\n{'='*60}")
print(f"{'FINAL COMPARISON — SimCLR vs MAE':^60}")
print(f"{'='*60}")
print(f"{'Metric':<22} {'SimCLR':>10} {'MAE':>10} {'Winner':>12}")
print(f"{'-'*60}")

winners = {'SimCLR': 0, 'MAE': 0}
rows    = [
    ('KNN Acc @20 (%)',    12.33,  11.17,  'SimCLR'),
    ('Silhouette (↑)',      0.326,  0.254,  'SimCLR'),
    ('Davies-Bouldin (↓)', 1.660,  1.488,  'MAE'),
    ('Alignment (↓)',       1.931,  0.779,  'MAE'),
    ('Uniformity (↓)',     -3.096, -0.938,  'SimCLR'),
]

for name, s, m, winner in rows:
    print(f"{name:<22} {s:>10.3f} {m:>10.3f} {winner:>12}")
    winners[winner] += 1

print(f"{'-'*60}")
print(f"{'SCORE':<22} {winners['SimCLR']:>10} {winners['MAE']:>10}")
print(f"{'='*60}\n")

# Bar chart
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# Chart 1 — metrics where higher is better
metrics_higher = ['KNN @20 (%)', 'Silhouette ×100']
simclr_vals    = [12.33, 32.64]
mae_vals       = [11.17, 25.45]

x = np.arange(len(metrics_higher))
axes[0].bar(x - 0.2, simclr_vals, 0.4, label='SimCLR', color='steelblue', alpha=0.8)
axes[0].bar(x + 0.2, mae_vals,    0.4, label='MAE',    color='coral',     alpha=0.8)
axes[0].set_xticks(x)
axes[0].set_xticklabels(metrics_higher)
axes[0].set_title('Higher is Better', fontsize=13)
axes[0].legend()
axes[0].set_ylabel('Score')

# Chart 2 — metrics where lower is better
metrics_lower = ['Davies-Bouldin', 'Alignment']
simclr_vals2  = [1.660, 1.931]
mae_vals2     = [1.488, 0.779]

x2 = np.arange(len(metrics_lower))
axes[1].bar(x2 - 0.2, simclr_vals2, 0.4, label='SimCLR', color='steelblue', alpha=0.8)
axes[1].bar(x2 + 0.2, mae_vals2,    0.4, label='MAE',    color='coral',     alpha=0.8)
axes[1].set_xticks(x2)
axes[1].set_xticklabels(metrics_lower)
axes[1].set_title('Lower is Better', fontsize=13)
axes[1].legend()
axes[1].set_ylabel('Score')

plt.suptitle('SimCLR vs MAE — Metric Comparison', fontsize=15)
plt.tight_layout()
plt.savefig(f"{PROJECT_DIR}/metrics_comparison.png", dpi=150, bbox_inches='tight')
plt.show()
print("Summary chart saved ✅")